modLoader="javafml"
loaderVersion="[39,)"
license="MIT License"
[[mods]]
modId="harderspawners"
version="${file.jarVersion}"
displayName="Harder Spawners Mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-spawners"
updateJSONURL="https://github.com/mactso/HarderSpawners/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='Harder Spawners Mod.'
[[dependencies.harderspawners]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.harderspawnwers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="SERVER"
